//
//  Instance.swift
//  App
//
//  Created by Jeroen Wesbeek on 03/05/2019.
//

import Vapor
import FluentSQLite

final class Instance: Codable {
    var id: UUID?
    /// The instance uuid as generated by the macOS app.
    var uuid: String
    /// The instance version that is running.
    var version: String
    /// The track of the instance.
    var track: String
    /// The ip of the machine running the instance.
    var ip: String
    /// The port on which the instance is exposed.
    var port: Int
    /// The full name of the user running the instance.
    var fullName: String
    /// The user name of the user running the instance.
    var userName: String
    
    var createdAt: Date?
    var updatedAt: Date?
    
    init(version: String, uuid: String, track: String, ip: String, port: Int, fullName: String, userName: String) {
        self.version = version
        self.uuid = uuid
        self.track = track
        self.ip = ip
        self.port = port
        self.fullName = fullName
        self.userName = userName
    }
}

extension Instance: SQLiteUUIDModel {
    static var createdAtKey: TimestampKey? = \.createdAt
    static var updatedAtKey: TimestampKey? = \.updatedAt
}

extension Instance: Migration {
    static func prepare(on connection: SQLiteConnection) -> Future<Void> {
        return Database.create(self, on: connection) { (builder) in
            try addProperties(to: builder)
            builder.unique(on: \.uuid)
        }
    }
}

extension Instance: Parameter { }

extension Instance: Content { }
